### ISSUE TITLE
Circulating Supply and Total Supply API Endpoints

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer#225]
Relates to #138 

Coinmarketcap requires `circulating supply` and `total supply` api endpoints for their statistics.

`Total Supply` = 252460800 + `Current Block Height`

`Circulating Supply` = `Total Supply` - `balance of this wallet https://poaexplorer.com/address/0x517f3acff3afc2fb45e574718bca6f919b798e10`

**Comment by igorbarinov** [comment]
I don't think they use the balance of the wallet in their calculations

**Comment by acravenho** [comment]
@igorbarinov CMC is getting their data from this endpoint https://poaexplorer.com/api/network. I am calculating circulating supply using that calculation. Does this need updating?

**Comment by igorbarinov** [comment]
You formula give the right results (which are not)
but it's not the right way to get them. The formula for the supply should not have wallets
here is the correct supply https://github.com/poanetwork/wiki/wiki/POA-Token-Supply

@SiddigZeidan we should not include 6 months unlock yet?

**Comment by acravenho** [comment]
My concern is that this formula will work for our chain but is not an easily configurable option for any other chain that will deploy this explorer. Most chains have single/multiple wallets where funds are locked. Configuring these wallets makes it easy for the end user to provide `circulating supply` through the api. 

What is the calculation for funds released at 6 months? Is it 25% per 6 months up to the 2 years vesting period?

**Comment by igorbarinov** [comment]
> My concern is that this formula will work for our chain but is not an easily configurable option for any other chain that will deploy this explorer. 

any other chain will figure out how to provide circulating supply. at the moment, we are interested in:
- POA Core
- POA Sokol
- ETH Mainnet
- ETH Testnets

> Most chains have single/multiple wallets where funds are locked. 

I don't support the idea of using balances of wallets in formulas. If a project will rebalance locked tokens between wallets it can affect market a lot. 

`Total Supply` = `Premine supply` + `Current Block Height`. Since 18 Nov 2018 it will be different 
 because of https://github.com/poanetwork/RFC/issues/14
Circulating Supply = Total Supply - Locked Supply
Locked Supply is a config param which an operator of the instance may chane

> What is the calculation for funds released at 6 months? Is it 25% per 6 months up to the 2 years vesting period?
```
2 years vesting with distribution every 3 months starting on the 6th month after mainnet launch. The first portion will be released in 6 months after the launch with the subsequent pro-rated 3 months distributions.
```
Means 1/4 unlocked after 6 months and 1/8 every 3 months during 18 months
1/4+1/8+1/8+1/8+1/8+1/8+1/8
6 months+3months+3months+3months+3months+3months+3months

**Comment by SiddigZeidan** [comment]
6 months should not be included yet

**Comment by DavidShanks1** [comment]
Hello, 

how do I fetch the market cap for any coin on bsc?
