### ISSUE TITLE
Performance Improvement: count queries

### ISSUE THREAD

**Issue by tmecklem** [poanetwork/poa-explorer#251]
The transactions page uses 
```sql
SELECT count(t0."hash") FROM "transactions" AS t0
```

to show the number of transactions in the database, which can be slow (.7 seconds on my partially indexed development environment of 4 million records).

Postgres has a much faster estimated count available via a statistics lookup on the catalog table via

```sql
SELECT reltuples AS approximate_row_count FROM pg_class WHERE relname = 'transactions'
```

This estimate isn't guaranteed to be exact, but executes on the same data set in 0.04 seconds. We should consider using these estimate queries for count lookups when precise numbers aren't critical.

**Comment by KronicDeth** [comment]
I can't think of anywhere we care about exact counts.  If we care about the block count we would use `MAX(blocks.number)` instead.  The only other heavy use of counts outside the UI is in the `DEBUG_INDEXER=1` logs, which can if wishy-washy because we can always manually do a query.

🤔  what if all the counts in the `DEBUG_INDEXER=1` log are slowing down the indexing.

**Comment by KronicDeth** [comment]
> These numbers are current as of the last VACUUM or ANALYZE on the table

-- https://www.postgresql.org/docs/current/static/row-estimation-examples.html

I'm not sure how often a `VACUUM` will trigger during an index.  They could be minutes out of date if it is based on a time or thousands of inserts.  It is something we need to experimentally verify when `AUTOVACUUM` is enabled and check how that works in RDS.

**Comment by acravenho** [comment]
@KronicDeth After implementing this change, page load time decreased from 6-10 seconds to almost instantaneous. I know it's being used quite a bit in indexer.
