### ISSUE TITLE
Update transactions list page design

### ISSUE THREAD

**Issue by jimmay5469** [poanetwork/poa-explorer#368]
Update transactions list page design to reflect the new direction settled on in #231.

**Comment by jimmay5469** [comment]
Reopening because we didn't run this through acceptance...

**Comment by acravenho** [comment]
Sorry @jimmay5469. After using the explorer for a few days I felt like there were some subtle things that could be improved upon. 

- [ ] Transaction status (#394 && #400)
- [ ] Add fee of the transaction
- [ ] The value right now is currently a light gray and doesn’t stand out. I’m wondering if we can make this standout more.
- [ ] Token transfers added to the main transactions list (will add link to the issue once it's refined by Plataformatec

**Comment by jimmay5469** [comment]
No worries, I didn't realize until after we merged that we hadn't added you as a reviewer to the PR.

**Comment by arthurra** [comment]
### Mock-ups for proposed changes:

![transaction-tile](https://user-images.githubusercontent.com/1641169/42708475-7022b4d8-86ab-11e8-874e-86810acedcf7.png)
![transaction-tile-token-transfer](https://user-images.githubusercontent.com/1641169/42708483-746e385a-86ab-11e8-8a5d-07063a394009.png)

**Comment by arthurra** [comment]
We have decided to slightly modify the design of the transaction tile. After testing the design more thoroughly it became clear the POA value and the USD value would fit next to each other horizontally give that the numbers could be quite long. Because of this, we decided to move the IN/OUT flag the left of the Block Height to make room for the POA value and the USD value to be on their own lines.

**Comment by arthurra** [comment]
![screen_shot_2018-07-16_at_2 44 53_pm](https://user-images.githubusercontent.com/1641169/42778122-1dbd3860-890a-11e8-8d9a-ce851ee102a0.png)
